- Chart.yaml
- templates/application-backup-hashicorp-vault.yaml
- templates/application-cert-manager-crd.yaml
- templates/application-cert-manager.yaml
- templates/application-external-dns.yaml
- templates/application-kube-prometheus-stack-crds.yaml
- templates/application-kube-prometheus-stack.yaml
- templates/application-loki-log-exporter-to-s3.yaml
- templates/application-loki.yaml
- templates/application-metacontroller.yaml
- templates/application-nginx-public.yaml
- templates/application-pomerium.yaml
- templates/application-promtail.yaml
- templates/application-pull-request-bot.yaml
- templates/application-vault.yaml
feat: update backup-hashicorp-vault from 0.2.1 -> 0.2.2
feat: update cert-manager from 0.11.1 -> 0.11.2
feat: update external-dns from bitnami version 6.18.0 -> 6.20.1
feat: update kube-prometheus-stack from 45.17.0 -> 45.27.2
feat: update loki log exporter from 0.1.0 -> 0.1.1
feat: update loki helm chart from 5.2.0 -> 5.5.1
feat: update metacontroller from 4.10.0 -> 4.10.3
feat: update ingress-nginx from 4.6.0 -> 4.6.1
feat: update pomerium from 0.1.0 -> 0.2.0
feat: update promtail from 6.10.0 -> 6.11.2
feat: update pull-request-bot from 0.4.0 -> 0.5.2
feat: update vault server from 1.13.1 -> 1.13.2
chore: bump glueops-platform helm chart version
> feat: monthly updates (#27)

- Chart.yaml
- README.md
- main.tf
- templates/application-backups-and-exports.yaml
- templates/application-cert-manager-crd.yaml
- templates/application-cert-manager.yaml
- templates/application-dex.yaml
- templates/application-external-dns.yaml
- templates/application-external-secrets-crd.yaml
- templates/application-external-secrets.yaml
- templates/application-glueops-alerts.yaml
- templates/application-glueops-grafana-dashboards.yaml
- templates/application-kube-prometheus-stack-crds.yaml
- templates/application-kube-prometheus-stack.yaml
- templates/application-loki-alert-group-controller.yaml
- templates/application-loki.yaml
- templates/application-metacontroller.yaml
- templates/application-nginx-public.yaml
- templates/application-pomerium-post-deploy.yaml
- templates/application-pomerium.yaml
- templates/application-promtail.yaml
- templates/application-pull-request-bot.yaml
- templates/application-strimzi.yaml
- templates/application-tenant-application-stack.yaml
- templates/application-vault-prerequisites.yaml
- templates/application-vault.yaml
- values.yaml
fix: added resources-finalizer.argocd.argoproj.io to all argocd applications so that things get cleaned up whenever things are removed.
fix: picked better port numbers for the various services that run on hostNetwork. ChatGPT recommended the ranges I picked
fix: added hostNetwork enabled flag so that we can deploy to clouds like digital ocean
> feat: adding resources finalizer to improve cleanup when removing argocd applications

- templates/application-cert-manager-crd.yaml
- templates/application-cert-manager.yaml
This needs to be merged/tagged/built/published first: https://github.com/GlueOps/platform-helm-chart-cert-manager/pull/14
> feat: update cert-manager from v1.12.2 -> v1.12.3

- templates/application-qr-code-generator.yaml
small change that we can include in the release or hold - we hadn't given an appName to the qr-code-generator, so it was called "example-app"
> style(qr-code-generator): name application

- Chart.yaml
- README.md
- templates/application-backups-and-exports.yaml
- templates/application-cert-manager-crd.yaml
- templates/application-cert-manager.yaml
- templates/application-cluster-info-page.yaml
- templates/application-external-secrets-crd.yaml
- templates/application-external-secrets.yaml
- templates/application-glueops-alerts.yaml
- templates/application-glueops-operator-waf-web-acl.yaml
- templates/application-glueops-operator-waf.yaml
- templates/application-kube-prometheus-stack-crds.yaml
- templates/application-kube-prometheus-stack.yaml
- templates/application-loki-alert-group-controller.yaml
- templates/application-loki.yaml
- templates/application-metacontroller.yaml
- templates/application-nginx-public.yaml
- templates/application-pomerium.yaml
- templates/application-promtail.yaml
- templates/application-pull-request-bot.yaml
- templates/application-qr-code-generator.yaml
- templates/application-vault-init-controller.yaml
- templates/application-vault.yaml
I branched this off release/v0.34.0 so we don't mess with his existing QA workflow
Notes:
feat: adding operator for WAF
feat: adding operator for WAF WebACL
MAJOR: new variables required:
- glueops_operators.waf.aws_accessKey
- glueops_operators.waf.aws_secretKey
- glueops_operators.web_acl.aws_accessKey
- glueops_operators.web_acl.aws_secretKey
feat: adding support to deploy WAF via app helm chart (0.4.0)
feat: updating backup tools:
- vault 1.14.3 -> 1.14.4
- loki 2.9.1 -> 2.9.2
- cert-manager 1.12.4 -> 1.12.5
feat: external-secrets 0.9.4 -> 0.9.6
- added retries for vault secret store (max 5 every 10s)
feat: kube-prometheus-stack 51.0.3 -> 51.9.2
- alertmanager v0.26.1 -> v0.26.2
- grafana 10.1.2 -> 10.1.5
feat: loki 5.22.0 -> 5.31.0
- app version of loki 2.9.1 -> 2.9.2
feat: …
> Release/prep for release of v0.34.0

- values.yaml
We have backups and unless all the data volumes get destroyed it shouldn't overwrite it
> feat: changing the default action to restore for vault init controller

- templates/application-nginx-public.yaml
[…hen the hostname doesn't match](feat: update ingress nginx v4.8.3 -> v4.8.4 and reject SSL requests when the hostname doesn't match)
> feat: update ingress nginx v4.8.3 -> v4.8.4 and reject SSL requests when the hostname doesn't match

- templates/application-vault.yaml
feat: change vault stateful set to use rollingUpdate when the container images change instead of requiring ondelete
ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
___
enhancement
___
- Changed the update strategy of the Vault StatefulSet to use `RollingUpdate` instead of requiring manual deletion for updates. This enhancement allows for seamless updates of container images without downtime.
___
<tr>
<td>
<details>
<summary><strong>application-vault.yaml</strong><dd><code>Implement RollingUpdate Strategy for Vault StatefulSet</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-vault.yaml …
> feat: change vault stateful set to use rollingUpdate when the container images change instead of requiring ondelete

- templates/application-metacontroller.yaml
enhancement
___
- Switched Metacontroller source from a Helm repository to an OCI repository format.
- Updated the `targetRevision` to align with the new source, removing the 'v' prefix for versioning.
___
<tr>
<td>
<details>
<summary><strong>application-metacontroller.yaml</strong><dd><code>Switch Metacontroller Source from Helm Repository to OCI Repository</code></dd></summary>
<hr>
templates/application-metacontroller.yaml
<li>Changed <code>repoURL</code> from Helm repository URL to OCI repository format.<br> <li> Updated <code>targetRevision</code> to remove the 'v' prefix.<br>
</details>
</td>
<td><a …
> feat(metacontroller): switch from helm repo to OCI repository

- values.yaml
bug_fix
___
- Corrected the tag for the metacontroller image in `values.yaml` to properly prefix with 'v', ensuring compatibility or correctness with image tagging conventions.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>values.yaml</strong><dd><code>Correct Metacontroller Image Tag Prefix</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
values.yaml
<li>Corrected the tag for the metacontroller image to include the 'v' <br>prefix.<br>
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/236/files#diff-8377b3e3740a3fcd9f682e5 …
> fix: tag for metacontroller

- Chart.yaml
enhancement
___
- Bumped chart version to `0.42.0-rc1` for the GlueOps Platform Helm chart.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump Chart Version for GlueOps Platform</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Bumped chart version from `0.41.0-rc3` to `0.42.0-rc1`.
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/237/files#diff-d954583aa4c24cff0039bc948abd7c694fc3dab2030231d11ed1b3cda9b4ddbe">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> chore: bump version to 0.42.0-rc1

- .github/workflows/helm-docs.yml
- Chart.yaml
- README.md
- templates/application-metacontroller.yaml
bug_fix
___
- Fixed the incorrect URI format for the metacontroller image in the Helm chart, ensuring proper image reference.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details>
<summary><strong>application-metacontroller.yaml</strong><dd><code>Fix Metacontroller Image URI in Helm Chart</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-metacontroller.yaml
<li>Corrected the format of the metacontroller image URI in the Helm chart <br>by replacing a colon (:) with a slash (/).<br>
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/239/files#diff-a …
> fix: metacontroller registry/repository uri

- templates/application-glueops-fluentbit.yaml
Bug fix
___
- Removed the `UploadTimeout` setting from the S3 configuration in the `application-glueops-fluentbit.yaml` template to revert to the default upload frequency.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details>
<summary><strong>application-glueops-fluentbit.yaml</strong><dd><code>Remove `UploadTimeout` setting from S3 configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-glueops-fluentbit.yaml
- Removed `UploadTimeout` setting from the S3 configuration.
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/297/files#diff-0718b27d68508cc34168550b467b620e2d3ecebd8877a8768fe47aa04a57493b">+0/-1</a …
> fix(fluentbit): reduce frequency of upload from 1m to default (10m)

- Chart.yaml
- README.md
- templates/application-external-dns.yaml
There appear to be bugs in v7 helm chart: https://github.com/bitnami/charts/issues/25967
___
Bug fix
___
- Reverted `external-dns` Helm chart version from `7.5.7` to `6.38.0` due to bugs in version 7.
- Referenced issue: https://github.com/bitnami/charts/issues/25967
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details>
<summary><strong>application-external-dns.yaml</strong><dd><code>Revert external-dns Helm chart version due to bugs</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-external-dns.yaml
<li>Reverted <code>external-dns</code> Helm chart version from <code>7.5.7</code> to <code>6.38.0</code>.<br>
</details>
</td>
<td><a …
> fix: revert external dns back to v6

- Chart.yaml
- README.md
- templates/application-glueops-alerts.yaml
Bug fix
___
- Excluded `argocd-redis-secret-*` pods from the `glueops-pod-in-bad-state` alert to prevent unnecessary alerts for the ArgoCD Redis init job.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>application-glueops-alerts.yaml</strong><dd><code>Remove alert for ArgoCD Redis init job</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-glueops-alerts.yaml
<li>Excluded <code>argocd-redis-secret-*</code> pods from the <code>glueops-pod-in-bad-state</code> <br>alert.<br>
</details>
</td>
<td><a …
> fix: remove alert for argocd redis init job

- README.md
- values.yaml
___
- Replaced hardcoded domains with dynamic placeholders in `README.md` and `values.yaml` for `loki.prefix`, `tempo.prefix`, and `thanos.prefix`.
- Improved documentation by updating domain references to use placeholders, enhancing flexibility and configurability.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Replace hardcoded domains with placeholders in README</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<li>Updated domain placeholders for <code>loki.prefix</code>, <code>tempo.prefix</code>, and <br><code>thanos.prefix</code>.<br> <li> Replaced hardcoded domain with dynamic …
> fix: remove hardcoded captain domain for new otel stack

- Chart.yaml
- README.md
- templates/application-external-dns.yaml
bug_fix, documentation
___
- Rolled back the `external-dns` chart version from 8.6.0 to 8.5.1 to address issues with the latest version using the OCI repository format.
- Updated the chart version in `Chart.yaml` from 0.53.3 to 0.53.4 for a hotfix release.
- Updated the version badge in `README.md` to reflect the new chart version 0.53.4.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart version for hotfix release</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Bumped chart version from 0.53.3 to …
> Fix rollback external dns. it appears the latest version uses oci repository format

- templates/application-vault-prerequisites.yaml
Enhancement
___
- Updated the target version of `glueops-vault-prerequisites` chart.
- Ensured compatibility with the new version 0.4.0.
___
<tr>
<td>
<details>
<summary><strong>application-vault-prerequisites.yaml</strong><dd><code>Update targetRevision to 0.4.0 for Helm chart</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-vault-prerequisites.yaml
<li>Updated <code>targetRevision</code> from 0.2.0 to 0.4.0.<br> <li> Ensured the Helm chart uses the latest version.
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/590/files#diff-8b3 …
> changed the prerequisite target version

- templates/application-loki.yaml
Bug fix
___
- Configure Loki canary to use custom registry instead of docker.io
___
```mermaid
flowchart LR
A["docker.io registry"] -- "replace with" --> B["custom registry mirror"]
B --> C["Loki canary image"]
```
<tr>
<td>
<details>
<summary><strong>application-loki.yaml</strong><dd><code>Configure custom registry for Loki canary</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-loki.yaml
<ul><li>Add image registry configuration for Loki canary<br> <li> Set registry to use …
> fix: loki canary is using docker.io and not one of our mirrors

- README.md
- templates/application-external-dns.yaml
- values.yaml
Enhancement
___
- Migrate external-dns from Bitnami Helm chart to official GitHub repository
- Update chart source from registry to Git repository with path-based deployment
- Restructure AWS credentials configuration from Helm parameters to environment variables
- Enhance RBAC permissions for additional Kubernetes resources access
___
```mermaid
flowchart LR
A["Bitnami Registry Chart"] -- "migrate to" --> B["GitHub Repository Chart"]
B --> C["Environment Variables Config"]
B --> D["Enhanced RBAC Permissions"]
C --> E["AWS Credentials Setup"]
D --> F["Extended Resource Access"]
```
<tr>
<td> …
> feat: migrate external-dns from bitnami to github
