GlueOps/platform-helm-chart-platform

Chart.yaml
templates/application-pull-request-bot.yaml

code changes: https://github.com/GlueOps/pull-request-bot/pull/12/files 
helm chart changes: https://github.com/GlueOps/platform-helm-chart-pull-request-bot/pull/3

MAJOR: we fixed pr bot support for appsets but now all appsets require additional annotations

---

templates/application-pomerium.yaml

https://github.com/GlueOps/platform-kustomize-pomerium/pull/4

feat: increasing resources for pomerium

---

Chart.yaml
templates/application-metacontroller.yaml

bump chart: 0.34.0-rc10 -> 0.34.0-rc11

chore(metacontroller): v4.11.1 -> v4.11.2

---

Chart.yaml
templates/application-metacontroller.yaml

chore(metacontroller): v4.11.2 -> v4.11.3

---

Chart.yaml
templates/application-metacontroller.yaml

chore(metacontroller): v4.11.3 -> v4.11.5

---

templates/application-kube-prometheus-stack-crds.yaml
templates/application-kube-prometheus-stack.yaml

feat: upgrade kube prometheus stack from 51.9.2 -> 5.10.0
feat: upgrade grafana 10.1.5 -> 10.2.0

feat: upgrade kube prometheus stack from 51.9.2 -> 5.10.0

---

Chart.yaml
templates/application-external-secrets-crd.yaml
templates/application-external-secrets.yaml

chore(external-secrets): glueops 0.5.2 -> 0.5.3, crd v0.9.7 -> v0.9.8

---

templates/application-glueops-operator-redis.yaml
templates/application-glueops-operator-waf.yaml
templates/application-metacontroller.yaml

related: https://github.com/GlueOps/metacontroller-operator-waf/pull/14

Fix metacontroller rate limits

---

Chart.yaml
templates/application-glueops-operator-waf.yaml

enhancement
___
- Updated the GlueOps Operator WAF image tag to `v0.5.2`.
- Incremented the chart version to `0.38.1` to reflect the update.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Increment Chart Version for GlueOps Platform</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Incremented chart version from 0.38.0 to 0.38.1.
</details>
</td>
<td><a href="https:/GlueOps/platform-helm-chart-platform/pull/176/files#diff-d954583aa4c24cff0039bc948abd7c694fc3dab2030231d11ed1b3cda9b4ddbe">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …

feat(operator-waf): v0.5.1 -> v0.5.2

---

README.md

enhancement
___
- This PR introduces a change in the update strategy for the Vault StatefulSet to use `RollingUpdate` instead of requiring manual deletion for updates. This enhancement ensures that updates to the container images are handled more gracefully, minimizing downtime and ensuring a smoother update process.
___
<tr>
<td>
<details>
<summary><strong>application-vault.yaml</strong><dd><code>Implement RollingUpdate Strategy for Vault StatefulSet</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-vault.yaml
<li>Added <code>updateStrategyType: "RollingUpdate"</code> to the Vault StatefulSet <br>configuration.<br>
</details>
</td> …

feat: update vault update strategy

---

templates/application-keda.yaml

enhancement
___
- Updated KEDA chart version to `2.13.2` in `templates/application-keda.yaml` to leverage the latest features and fixes.
___
<tr>
<td>
<details>
<summary><strong>application-keda.yaml</strong><dd><code>Update KEDA Chart Version to 2.13.2</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-keda.yaml
<li>Updated the <code>targetRevision</code> for the KEDA chart from <code>2.11.2</code> to <code>2.13.2</code>.<br>
</details>
</td>
<td><a …

feat: update keda to latest version

---

templates/application-external-dns.yaml

enhancement
___
- Updated the external-dns chart version to 6.38.0 in `application-external-dns.yaml` to leverage new features and bug fixes.
___
<tr>
<td>
<details>
<summary><strong>application-external-dns.yaml</strong><dd><code>Update external-dns Chart Version to 6.38.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-external-dns.yaml
<li>Updated the <code>targetRevision</code> for the external-dns chart from 6.32.1 to <br>6.38.0.<br>
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/185/files#diff-77f505fbaa80b2a …

feat: update-external-dns to 6.38.0

---

templates/application-dex.yaml

enhancement
___
- Updated Dex Helm chart version to `0.16.0`.
- Updated Dex image version to `v2.38.0`.
- These updates ensure compatibility with newer features and security patches.
___
<tr>
<td>
<details>
<summary><strong>application-dex.yaml</strong><dd><code>Update Dex Helm Chart and Image Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-dex.yaml
<li>Updated the <code>targetRevision</code> of the dex chart from <code>0.15.3</code> to <code>0.16.0</code>.<br> <li> Updated the dex image tag from <code>v2.37.0</code> to …

feat: update dex helm chart to 0.16.0 and dex version to 2.38.0

---

templates/application-cluster-info-page.yaml

enhancement
___
- The `cluster-information-help-page-html` image in the `application-cluster-info-page.yaml` file has been updated to use the latest tag (`v0.1.2`). This ensures the cluster info page uses the most recent version of nginx.
___
<tr>
<td>
<details>
<summary><strong>application-cluster-info-page.yaml</strong><dd><code>Update Cluster Info Page Image to Latest Version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-cluster-info-page.yaml
<li>Updated the <code>tag</code> for the <code>cluster-information-help-page-html</code> image from <br><code>v0.1.1</code> to …

feat: updating cluster-info-page image to use latest version of nginx

---

Chart.yaml
README.md
main.tf
templates/application-backups-and-exports.yaml
templates/application-cert-manager-crd.yaml
templates/application-cert-manager.yaml
templates/application-glueops-alerts.yaml
values.yaml

___
- Added variables and configurations for TLS certificate backup and restore, including AWS credentials and S3 key prefix.
- Updated chart version to 0.41.0-rc3.
- Updated README with the new chart version badge.
- Added a new backup job for TLS certificates with corresponding service account and RBAC.
- Updated cert-manager CRDs to version 1.13.5 and enhanced cert-manager configuration.
- Modified alert expressions to include additional namespaces and conditions.
- Added values for TLS certificate backup and restore in `values.yaml`.
___
<tr>
<td>
<details>
<summary><strong>main.tf</strong><dd><code>Add TLS Certificate …

feat: adding cert-manager backup and restore, update cert-manager to v1.13.5, add pomerium alerting

---

templates/application-backups-and-exports.yaml
templates/application-cluster-info-page.yaml
templates/application-dex.yaml
templates/application-glueops-alerts.yaml
templates/application-glueops-operator-redis.yaml
templates/application-glueops-operator-waf-web-acl.yaml
templates/application-glueops-operator-waf.yaml
templates/application-kube-prometheus-stack.yaml
templates/application-loki-alert-group-controller.yaml
templates/application-loki.yaml
templates/application-network-exporter.yaml
templates/application-promtail.yaml
templates/application-pull-request-bot.yaml
templates/application-qr-code-generator.yaml
templates/application-vault-init-controller.yaml
templates/application-vault.yaml
values.yaml

enhancement
___
- Migrated container image definitions for multiple applications to `values.yaml`, enhancing maintainability and configurability.
- Updated registry, repository, and tag information for each application's container image in `values.yaml`.
- Applications include backup_and_exports, cluster info page, Dex, GlueOps Alerts, GlueOps Operator Redis, GlueOps Operator WAF and WAF Web ACL, Grafana in Kube-Prometheus-Stack, Loki Alert Group Controller, Loki, Network Exporter, Promtail, Pull Request Bot, QR Code Generator, Vault Init Controller, and Vault.
___
</strong></td><td><details><summary>16 files</summary><table>
<tr>
<td>
<details> …

feat: migrating container definitions for all argocd apps except ingress nginx to the main values.yaml

---

templates/application-kube-prometheus-stack-crds.yaml

enhancement
___
- Updated the `targetRevision` in the kube-prometheus-stack CRDs to `v57.2.0` to keep the dependencies up to date.
___
<tr>
<td>
<details>
<summary><strong>application-kube-prometheus-stack-crds.yaml</strong><dd><code>Update kube-prometheus-stack CRDs to v57.2.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-kube-prometheus-stack-crds.yaml
<li>Updated the <code>targetRevision</code> for kube-prometheus-stack CRDs to <code>v57.2.0</code>.<br>
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/223/fil …

chore(deps): update helm release kube-prometheus-stack CRDS to v57.2.0

---

templates/application-metacontroller.yaml
values.yaml

Renovatebot should start pinning it after this PR.

Chore(deps) metacontroller pinning

---

values.yaml

enhancement
___
- Pinned the `metacontroller` docker image in the `values.yaml` file to a specific SHA digest. This change aims to enhance reliability and consistency by using a fixed image version.
___
<tr>
<td>
<details>
<summary><strong>values.yaml</strong><dd><code>Pin Metacontroller Docker Image to SHA Digest</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
values.yaml
<li>Pinned the <code>metacontroller</code> docker image to a specific SHA digest to <br>ensure reliability and consistency.<br>
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/ …

chore(deps): pin metacontroller docker image

---

README.md

___
- Updated the chart version in `README.md` to 0.42.0-rc1.
- Introduced new container image configurations for backup tools, certs backup restore, vault backup validator, cluster information help page, dex, cluster monitoring, shared redis, WAF operator, WAF web ACL, Grafana, Loki, Loki alert group controller, metacontroller, network exporter, promtail, pull request bot, QR code generator, Vault, and Vault init controller.
- Updated tags for existing container images to newer versions, ensuring the use of up-to-date and secure software components.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Update …

docs: automated helm-docs action

---

Chart.yaml
README.md
templates/application-glueops-grafana-dashboards.yaml

___
- Bumped the chart version in `Chart.yaml` from `0.43.0-rc12` to `0.43.0-rc13`.
- Updated the version badge in `README.md` to reflect the new chart version `0.43.0-rc13`.
- Updated the `targetRevision` of the `glueops-grafana-dashboards` chart in `templates/application-glueops-grafana-dashboards.yaml` from `0.10.1` to `0.12.0`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart version to `0.43.0-rc13`.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Updated …

Venkatamutyala patch 1

---

templates/application-kube-prometheus-stack.yaml

This PR will add remoteWrite to cortex in prometheus

feat: add remoteWrite to cortex in prometheus

---

Chart.yaml
README.md

enhancement
___
- Bumped the chart version from `0.45.0-rc1` to `0.45.0-rc2` in `Chart.yaml`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart version to `0.45.0-rc2`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Bumped the chart version from `0.45.0-rc1` to `0.45.0-rc2`.
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/340/files#diff-d954583aa4c24cff0039bc948abd7c694fc3dab2030231d11ed1b3cda9b4ddbe">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …

feat: bump for next rc

---

templates/application-cert-manager-crd.yaml

This needs another approval too: https://github.com/GlueOps/cert-manager-crds/pulls

feat: update cert-manager CRDs

---

templates/application-nginx-public.yaml

enhancement
___
- Updated the `controller` image tag in the `application-nginx-public.yaml` template from `v1.9.6` to `v1.11.1`.
___
<tr>
<td>
<details>
<summary><strong>application-nginx-public.yaml</strong><dd><code>Update controller image tag to v1.11.1</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-nginx-public.yaml
- Updated the `controller` image tag from `v1.9.6` to `v1.11.1`.
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/402/files#diff-b8951700ccd41112fa2d2a037fe78e1b4f6e …

feat(nginx): update controller image tag

---

Chart.yaml
README.md

enhancement
___
- Updated the `version` field in `Chart.yaml` from `0.46.1` to `0.47.0` to prepare for a new release.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart version for new release</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Updated the `version` field from `0.46.1` to `0.47.0`.
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/405/files#diff-d954583aa4c24cff0039bc948abd7c694fc3dab2030231d11ed1b3cda9b4ddbe">+1/-1</a>&nbsp; &nbsp; …

feat: updating version for release

---

Chart.yaml
README.md

other
___
- Updated the version in `Chart.yaml` to `0.48.0` to prepare for the new release.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart version for new release</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Updated the chart version from `0.47.2` to `0.48.0`.
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/427/files#diff-d954583aa4c24cff0039bc948abd7c694fc3dab2030231d11ed1b3cda9b4ddbe">+1/-1</a>&nbsp; &nbsp; &nbsp; …

chore: bump version for release (v0.48.0)

---

Chart.yaml
README.md

other
___
- Bumped the version in `Chart.yaml` from `0.48.1` to `0.49.0` to reflect the new release.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart version to 0.49.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Updated the chart version from `0.48.1` to `0.49.0`.
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/432/files#diff-d954583aa4c24cff0039bc948abd7c694fc3dab2030231d11ed1 …

chore: bump version v0.48.1 -> v0.49.0

---

Chart.yaml
README.md
main.tf

___
- Removed variables related to Loki exporter and WAF/WebACL credentials from `main.tf`.
- Updated `helm_values` output in `main.tf` to exclude removed variables.
- Bumped chart version in `Chart.yaml` from 0.50.0 to 0.51.0.
- Updated version badge in `README.md` to reflect new chart version 0.51.0.
___
<tr>
<td>
<details>
<summary><strong>main.tf</strong><dd><code>Remove Loki exporter and WAF/WebACL variables</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
main.tf
<li>Removed variables related to Loki exporter and WAF/WebACL credentials.<br> <li> Updated …

Major removing loki exporter and waf/webacl keys

---

Chart.yaml
README.md
main.tf

enhancement
___
- Simplified the `replace` function calls in the `helm_values` output by reducing the number of nested `replace` functions from 37 to 1. This change enhances readability and maintainability of the code.
___
<tr>
<td>
<details>
<summary><strong>main.tf</strong><dd><code>Simplify nested replace function calls in helm_values</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
main.tf
<li>Simplified the <code>replace</code> function calls in the <code>helm_values</code> output.<br> <li> Reduced the number of nested <code>replace</code> functions from 37 to 1.<br>
</details>
</td>
<td><a …

fix: replaces

---

Chart.yaml
README.md

enhancement
___
- Updated the Helm chart version in `Chart.yaml` from 0.51.1 to 0.52.0 to reflect new changes or improvements in the GlueOps Platform.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update Helm chart version to 0.52.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Updated the chart version from 0.51.1 to 0.52.0.
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/526/files#diff-d954583aa4c24cff0039bc948abd7c694fc3dab2030231d11ed1b3cda9 …

feat: update chart.yaml to version: 0.52.0

---

Chart.yaml
README.md
templates/application-nginx-public.yaml

___
- Bumped the Nginx image tag in `templates/application-nginx-public.yaml` from v1.11.1 to v1.11.3 to ensure the latest features and security updates.
- Updated the chart version in `Chart.yaml` from 0.52.0 to 0.52.1.
- Updated the version badge in `README.md` to reflect the new chart version 0.52.1.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart version to 0.52.1</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

Fix bump nginx version to v1.11.3

---

otel/otel-operator.yaml

enhancement
___
- Reformatted the YAML file to improve readability and maintain consistency, which helps avoid continuous diffs in ArgoCD.
- Adjusted the indentation and reordered sections logically to enhance clarity.
___
<tr>
<td>
<details>
<summary><strong>otel-operator.yaml</strong><dd><code>Reformat YAML to improve readability and consistency</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
otel/otel-operator.yaml
<li>Reformatted YAML configuration for better readability.<br> <li> Adjusted indentation for consistency.<br> <li> Reordered sections for logical grouping.<br>
</details>
</td>
<td><a …

fix: yaml formatting to avoid continuous diff in argocd

---

Chart.yaml
README.md
templates/application-nginx-public.yaml

bug_fix, other
___
- Corrected the references in `templates/application-nginx-public.yaml` to fix the ingress nginx values, changing the path from `controller` to `image.controller`.
- Updated the chart version in `Chart.yaml` from 0.53.0 to 0.53.1 to reflect the hotfix.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Other</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart version for hotfix release</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Updated chart version from 0.53.0 to 0.53.1.
</details>
</td>
<td><a …

Fix ingress nginx values.yaml refs

---

Chart.yaml
README.md
templates/application-nginx-public.yaml

bug_fix, documentation
___
- Updated the Helm chart version from 0.53.4 to 0.53.5 in `Chart.yaml` and `README.md`.
- Added an empty `digest` field to the nginx controller image configuration in `application-nginx-public.yaml` to fix issues with digest handling.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart version to 0.53.5</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Updated chart version from 0.53.4 to 0.53.5.
</details>
</td> …

Fix nginx chart seems to add the digest. blanking it out fixes it as renovate also adds the digest of the container being used

---

Chart.yaml
README.md

Documentation, Other
___
- Updated Helm chart version from `0.54.0` to `0.54.1`.
- Updated README badge to reflect the new version.
- Automated documentation update using helm-docs.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update Helm chart version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Bumped chart version from `0.54.0` to `0.54.1`.
</details>
</td>
<td><a …

Change chart

---

Chart.yaml
README.md

___
- Updated Helm chart version from `0.54.1` to `0.54.2`.
- Updated README to reflect the new chart version.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bumped Helm chart version to 0.54.2</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Updated the `version` field from `0.54.1` to `0.54.2`.
</details>
</td>
<td><a href="https://github.com/GlueOps/platform-helm-chart-platform/pull/593/files#diff-d954583aa4c24cff0039bc948abd7c694fc3dab2030231d11ed1b3cda9b4ddbe" …

chore: bump version for release

---

Chart.yaml
README.md

Other
___
- Bump Helm chart version from 0.60.0 to 0.60.1
- Update version badge in documentation
___
```mermaid
flowchart LR
A["Chart.yaml"] -- "version bump" --> B["0.60.1"]
B -- "automated update" --> C["README.md badge"]
```
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart version to 0.60.1</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Increment chart version from …

chore: bumps chart version

---

templates/application-external-dns.yaml

Other
___
- Downgrade external-dns chart version from 8.9.2 to 8.7.5
___
```mermaid
flowchart LR
A["external-dns 8.9.2"] -- "downgrade" --> B["external-dns 8.7.5"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>application-external-dns.yaml</strong><dd><code>Downgrade external-dns chart version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
templates/application-external-dns.yaml
- Changed `targetRevision` from 8.9.2 to 8.7.5
</details>
</td>
<td><a …

chore: downgrade external-dns to 8.7.5

---

Chart.yaml
README.md

Other
___
- Bump Helm chart version from 0.60.4 to 0.60.6
- Update README badge to reflect new version
___
```mermaid
flowchart LR
A["Chart.yaml"] -- "version bump" --> B["0.60.6"]
B -- "automated update" --> C["README.md badge"]
```
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Version bump to 0.60.6</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

chore: bump chart

---

Chart.yaml
README.md

Enhancement
___
- Bump Helm chart version from 0.60.7 to 0.61.0
___
```mermaid
flowchart LR
A["Chart.yaml v0.60.7"] --> B["Chart.yaml v0.61.0"]
```
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Version bump to 0.61.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Chart.yaml
- Updated version field from 0.60.7 to 0.61.0
</details>
</td>
<td><a …

feat: Bump version to 0.61.0
